-- move to the correct schema
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = DEMO;

-- init db
CREATE TABLE DUMMY (
    ID VARCHAR (255) PRIMARY KEY
);

INSERT INTO DUMMY(ID) VALUES('DUMMY');